[build]
dockerfilePath = "apps/mmd-public/Dockerfile"
watchPatterns = [
  "apps/mmd-public/**",
  "libs/visualizations/**",
  "package.json",
  "package-lock.json"
]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
